using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using HoloToolkit.Unity.InputModule;

namespace HoloToolkit.Unity
{
    public class viewViolationContent : MonoBehaviour
    {

        public GameObject linkedViolation;
        public GameObject viewViolationHolder;
        public Text ViolationName;
        public Text DueDate;
        public Text metaDate;
        public Text Severity;

        // Use this for initialization
        void Start()
        {

        }

        // Update is called once per frame
        void Update()
        {

        }

        public void openContent()
        {
            linkedViolation.GetComponent<violationController>().linkedNode.GetComponent<violationNodeController>().openViolation();
            viewViolationHolder.GetComponent<viewViolationController>().closeViewer();
        }
    }
}